# the email account
user = 'xxx@hotmail.com'

# the app password for the email account
pwd = 'abcdefghijklmnop'

# add any keyword to this list, the program will automatically do both the phrase as well as the phrase without spaces
junk_keywords = [
    'offer',
    'affiliate',
    'associate',
    'pretty litter',
    'wild seafood',
    'wild_seafood',
    'wild | seafood',
    'leaf filter',
    'warranty',
    'sivana east',
    'silver singles',
    'elite singles',
    'seniors singles',
    'adt',
    'easy canvas prints',
    'life insurance',
    'arwhome',
    'invisible braces',
    'modernize roofing',
    'who\'s who',
    'annuities.com',
    'bagel kings of new york',
    'luxury card',
    'gold co',
    'cpap',
    'standard bank',
    'concealed',
    'cample jeun',
    'mcaffee',
    'mcafee',
    'glucose monitor',
    'loans',
    'protecting wealth',
    'mortgage',
    'hair la vie',
    'solar bright',
    'tommy chong',
    'amy myers',
    'splash wine',
    'daily purr',
    'sono bello',
    'lending',
    'burial',
    'gutter',
    'home insurance',
    'stolen liberties',
    'g-plans',
    'ethos life',
    'ethos ad',
    'blissy',
    'select quote',
    'energy bill',
    '1 ink',
    '1-ink',
    '1_ink',
    '1 i n k',
    'in bathtub',
    'get skinny chocolate',
    'invisible aligners',
    'saatva',
    'leaky gut',
    'indigo credit',
    'indigo card',
    'indigo platinum',
    'indigo mastercard',
    'usa military savings',
    'audiobooks',
    'amerisave',
    'carshield',
    'workerscompclaim',
    'compclaim',
    'ad partner',
    'advertising partner',
    'match seniors',
    'harrys',
    'notification@delivery.com',
    'hvac',
    'mcaffee',
    'timeshare',
    'advertisement',
    'walkin tub for seniors',
    'mint mobile partner',
    'bath and shower pros',
    'green chef',
    'hearing_aid',
    'hearing aid',
    'hearing-aid',
    'green light',
    'car accident',
    'life line',
    'weed killer',
    'weed-killer',
    'haven life',
    'every plate',
    'amo-latinas',
    'home light',
    '=',
    'honeycomb',
    'george foreman',
    'zoosk',
    'zippy loan',
    'gadgets junkies',
    'neuropathy treatment group',
    'smile advisors',
    'vivint',
    'eharmony',
    'seniors saving',
    'toxic water',
    'pro compression',
    'keranique',
    'trugreen',
    'terminix',
    'sonic bug',
    'empire today',
    'personal injury',
    'higher income',
    'total visa',
]

server = 'outlook.office365.com'
port = 993
